version: '3.1'

services:
  nginx:
   image: owasp/modsecurity-crs:nginx
   restart: always
   links:
    - wordpress
   ports:
    - 9080:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./modsecurity.d/setup.conf:/etc/modsecurity.d/setup.conf
    - ./modsecurity.d/modsecurity-override.conf:/etc/modsecurity.d/modsecurity-override.conf
    - /mnt/partition2/wordpress-container/html:/var/www/html
    - wordpress_var_run:/var/run
   command: >
    /bin/sh -c "echo 'SecRuleRemoveById 921110' >  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 932130'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 932100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941160'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941180'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941310'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 942100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 949110'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 953100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 950140'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 951240'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 959100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 200002'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 200003'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRequestBodyLimit 536870912'       >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    envsubst < /etc/nginx/templates/modsecurity.d/setup.conf.template > /etc/modsecurity.d/setup.conf &&
    envsubst < /etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template > /etc/modsecurity.d/modsecurity-override.conf &&
    nginx -g 'daemon off;'"
   tmpfs:
    - /var/cache/nginx/fastcgi_cache
    - /var/cache/nginx/fastcgi_temp

  wordpress:
   build:
    context: wordpress
   restart: always
   links:
    - db
   volumes:
    - ./wordpress/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - /mnt/partition2/wordpress-container/html:/var/www/html
    - wordpress_var_run:/var/run
   tmpfs:
    #- /var/www/html/wp-content/plugins/001-prime-strategy-translate-accelerator/cache:uid=33,gid=33
    - /tmp/wordpress:uid=33,gid=33

  db:
   image: jsurf/rpi-mariadb:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: bitnami_wordpress
   volumes:
    - ./db/accelerate.conf:/etc/mysql/conf.d/accelerate.conf
    - /mnt/partition2/wordpress-container/mysql:/var/lib/mysql
    - wordpress_var_run:/var/run

volumes:
  wordpress_var_run:
