version: '3.1'

services:
  nginx:
   image: owasp/modsecurity-crs:nginx
   restart: always
   links:
    - wordpress
   ports:
    - 9080:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./html:/var/www/html
    - wordpress_var_run:/var/run
   tmpfs:
    - /var/cache/nginx/fastcgi_cache
    - /var/cache/nginx/fastcgi_temp

  wordpress:
   build:
    context: wordpress
   restart: always
   links:
    - db
   volumes:
    - ./wordpress/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - ./html:/var/www/html
    - wordpress_var_run:/var/run
   tmpfs:
    - /var/www/html/wp-content/plugins/001-prime-strategy-translate-accelerator/cache:uid=33,gid=33
    - /tmp/wordpress:uid=33,gid=33

  db:
   image: jsurf/rpi-mariadb:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: bitnami_wordpress
   volumes:
    - ./db/accelerate.conf:/etc/mysql/conf.d/accelerate.conf
    - ./mysql:/var/lib/mysql
    - wordpress_var_run:/var/run

volumes:
  wordpress_var_run:
