version: '3.1'

services:
  nginx:
   image: nginx:latest
   restart: always
   links:
    - wordpress
   ports:
    - 9080:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./html:/var/www/html

  wordpress:
   build:
    context: wordpress
   restart: always
   links:
    - db
   volumes:
    - ./html:/var/www/html

  db:
   image: jsurf/rpi-mariadb:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: bitnami_wordpress
   volumes:
    - ./mysql:/var/lib/mysql
