version: '3.1'

services:
  nginx:
   image: nginx:latest
   restart: always
   links:
    - wordpress
   ports:
    - 9080:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./html:/var/www/html
   tmpfs:
    - /var/cache/nginx/fastcgi_cache

  wordpress:
   build:
    context: wordpress
   restart: always
   links:
    - db
   volumes:
    - ./html:/var/www/html
   tmpfs:
    - /var/www/html/wp-content/cache/autoptimize/1

  db:
   image: jsurf/rpi-mariadb:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: bitnami_wordpress
   volumes:
    - ./db/accelerate.conf:/etc/mysql/conf.d/accelerate.conf
    - ./mysql:/var/lib/mysql
