version: '3.1'

services:
  nginx:
   image: owasp/modsecurity-crs:nginx
   restart: always
   env_file: ./.env
   links:
    - wordpress
   ports:
    - $HOST_NGINX_PORT:$CONTAINER_NGINX_PORT
   volumes:
    - ./nginx:/nginx
    - ./nginx/conf.d/modsecurity.conf:/etc/nginx/conf.d/modsecurity.conf
    - $HOST_WEBROOT_DIR:$CONTAINER_WEBROOT_DIR
    - wordpress_var_run:/var/run
   command: >
    /bin/sh -c "echo 'SecRuleRemoveById 921110' >  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 932130'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 932100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941160'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941180'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 941310'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 942100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 949110'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 953100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 950140'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 951240'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 959100'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 200002'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRuleRemoveById 200003'            >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    echo 'SecRequestBodyLimit 536870912'       >>  /etc/modsecurity.d/owasp-crs/rules/zz-wordpress.conf &&
    envsubst '$$NGINX_USER' < /nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
    envsubst '$$NGINX_SERVER_NAME$$NGINX_WWW_SERVER_NAME$$NGINX_ROOT' < /nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
    envsubst < /etc/nginx/templates/modsecurity.d/setup.conf.template > /etc/modsecurity.d/setup.conf &&
    envsubst < /etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template > /etc/modsecurity.d/modsecurity-override.conf &&
    nginx -g 'daemon off;'"
   tmpfs:
    - /var/cache/nginx/fastcgi_cache
    - /var/cache/nginx/fastcgi_temp

  wordpress:
   build:
    context: wordpress
   restart: always
   env_file: ./.env
   links:
    - db
   volumes:
    - ./wordpress/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - $HOST_WEBROOT_DIR:$CONTAINER_WEBROOT_DIR
    - wordpress_var_run:/var/run
   tmpfs:
    #- $CONTAINER_WEBROOT_DIR/wp-content/plugins/001-prime-strategy-translate-accelerator/cache:uid=33,gid=33
    - /tmp/wordpress:uid=33,gid=33

  db:
   image: mariadb:latest
   restart: always
   env_file: ./.env
   volumes:
    - ./db/accelerate.conf:/etc/mysql/conf.d/accelerate.conf
    - $HOST_MYSQL_DIR:$CONTAINER_MYSQL_DIR
    - wordpress_var_run:/var/run

volumes:
  wordpress_var_run:
